# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  # daily "express" updates
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    commit-message:
      prefix: "express deps"
      prefix-development: "express dev deps"
      include: "scope"
    schedule:
      interval: "daily"
    allow:      
      - dependency-name: "yt*"
      
      - dependency-name: "electron-*"
      
      # dev dependencies      
      - dependency-name: "@electron/notarize"
        dependency-type: "development"
      
      - dependency-name: "electron"
        dependency-type: "development"
        
      - dependency-name: "electron-builder*"
        dependency-type: "development"
        
  # regular weekly updates for less critical packages
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "deps"
      prefix-development: "dev deps"
      include: "scope"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "lodash"
    
      - dependency-name: "svelte-spa-router"
        dependency-type: "production"
      
      # dev dependencies
      - dependency-name: "svelte*"
        dependency-type: "development"
        
      - dependency-name: "@tsconfig*"
        dependency-type: "development"
        
      - dependency-name: "@rollup*"
        dependency-type: "development"
        
      - dependency-name: "rollup*"
        dependency-type: "development"
      
  # ensure ci actions are fully up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci"
      include: "scope"
    schedule:
      interval: "weekly"
