# configuration file for `electron-builder` options
# i wanted these in a separate file for readability/simplicity, which is also why i went with toml
productName = "Theia"
appId = "co.cl0vr.theia.dl"
copyright = "Copyright © 2023 cl0vr"

afterSign = "./utils/notarize_config.js"

[mac]
category = "public.app-category.music"
hardenedRuntime = true
entitlements = "./build/entitlements.mac.plist"
entitlementsInherit = "./build/entitlements.mac.plist"

[dmg]
title = "Install Theia"

[dmg.window]
width = 540
height = 380

[[dmg.contents]]
x = 110
y = 190

[[dmg.contents]]
x = 430
y = 190
type = "link"
path = "/Applications"

# [linux]
# target = ["AppImage", "deb", "tar.gz"]

[win]
target = "nsis"
artifactName = "Install ${productName} v${version}.${ext}"
