# configuration file for `electron-builder` options
# i wanted these in a separate file for readability/simplicity, which is also why i went with toml
productName = "Theia"
appId = "co.cl0vr.theia.dl"
copyright = "Copyright © 2023 cl0vr"

generateUpdatesFilesForAllChannels = true

afterSign = "./utils/notarize_config.js"

files = [
    "**/src/app.toml",
    "**/package.json",
    "**/tsconfig.json",
    "**/README.md",
    "**/LICENSE.md",
    "**/src/background/*",
    "**/src/renderer/public/global.d.ts",
    "**/src/renderer/public/**",
    "!**/node_modules/*/{CHANGELOG.md,README.md,README,readme.md,readme}",
    "!**/node_modules/*/{test,__tests__,tests,powered-test,example,examples}",
    "!**/node_modules/*.d.ts",
    "!**/node_modules/.bin",
    "!**/asar-out-debug/*",
    "!**/*.{iml,o,hprof,orig,pyc,pyo,rbc,swp,csproj,sln,xproj}",
    "!.editorconfig",
    "!.prettier*",
    "!**/._*",
    "!**/{.DS_Store,.git,.hg,.svn,CVS,RCS,SCCS,.gitignore,.gitattributes}",
    "!**/{__pycache__,thumbs.db,.flowconfig,.idea,.vs,.nyc_output}",
    "!**/{appveyor.yml,.travis.yml,circle.yml}",
    "!**/{npm-debug.log,yarn.lock,.yarn-integrity,.yarn-metadata.json}",
]

# [publish]
# provider = "github"
# releaseType = "prerelease"


[mac]
category = "public.app-category.music"
hardenedRuntime = true
entitlements = "./build/entitlements.mac.plist"
entitlementsInherit = "./build/entitlements.mac.plist"
# target = { target = "default", arch = ['x64', 'arm64'] } # uncomment this line to disable universal builds

[dmg]
title = "Install Theia"

[dmg.window]
width = 540
height = 380

[[dmg.contents]]
x = 110
y = 190

[[dmg.contents]]
x = 430
y = 190
type = "link"
path = "/Applications"

# [linux]
# target = ["AppImage", "deb", "tar.gz"]

[win]
target = "nsis"
artifactName = "Install ${productName} v${version}.${ext}"
